'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FloseCode.UpdateLib.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Boarisch
        '''msgUpdateBereitsVorhanden=Es gibt scho a Update!\n\nZum Installiern, muasst as {0} Programm neistartn.
        '''msgUpdateLokaleInstallationNichtVollständig=De Installation is kaputt. Lods Programm nei runter und installiers nommoi.
        '''Update=Neie Version vom {0} Programm
        '''msgUpdateVorhanden=Es gibt a Update auf Version {0}.\n\nMogst des jetz obalon?
        '''ShowReleasenotes=Zoag wos neis gibt
        '''WarningNetFrameworkTooOld=Obacht: .Net Framework {0} (oder a kompatible Mono version) brauchts für des Upd [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Bavarian() As String
            Get
                Return ResourceManager.GetString("Bavarian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Български
        '''msgUpdateBereitsVorhanden=Ъпдейтът вече е свален!\n\nРестартирайте {0}, за да го инсталирате.
        '''msgUpdateLokaleInstallationNichtVollständig=
        '''Update={0} ъпдейт
        '''msgUpdateVorhanden=Съществува ъпдейт на версия {0}.\n\nИскате ли да го свалите сега?
        '''ShowReleasenotes=
        '''WarningNetFrameworkTooOld=
        '''WarningNetFrameworkUnknown=
        '''NetFrameworkDownload=
        '''Herunterladen=
        '''msgUpdateInstallierenAdmin=Вече сте свалили един ъпдейт, но не сте го инсталирали.\n\nСтартирайте програмата {0} като админи [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Bulgarian() As String
            Get
                Return ResourceManager.GetString("Bulgarian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=汉语
        '''msgUpdateBereitsVorhanden=你已下载了的更新。\n\n重新启动{0}来安装它。
        '''msgUpdateLokaleInstallationNichtVollständig=
        '''Update={0}更新
        '''msgUpdateVorhanden=有一个更新版本{0}\n\n你想现在就下载吗？
        '''ShowReleasenotes=
        '''WarningNetFrameworkTooOld=
        '''WarningNetFrameworkUnknown=
        '''NetFrameworkDownload=
        '''Herunterladen=
        '''msgUpdateInstallierenAdmin=您已下载了一个更新，但是你还没有安装了它。\n\n启动{0}以管理员身份来安装更新。
        '''msgKeinUpdate=现在没有更新
        '''msgFehlerUpdateSuchen=出错搜索更新的时候：{0}
        '''lblAktuelleDatei=当前文件：{0}
        '''UpdateFertigstellen=完成制订... ...
        '''msgUpdateErfolgreich=成功了下载更新！\ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Chinese() As String
            Get
                Return ResourceManager.GetString("Chinese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Dansk
        '''msgUpdateBereitsVorhanden=Du har allerede hentet en opdatering.\n\nGenstart {0}for at installere.
        '''msgUpdateLokaleInstallationNichtVollständig=
        '''Update={0} opdater
        '''msgUpdateVorhanden=Opdatering til version {0}er nu tilgængelig.\n\nØnsker du at hente den nu?
        '''ShowReleasenotes=
        '''WarningNetFrameworkTooOld=
        '''WarningNetFrameworkUnknown=
        '''NetFrameworkDownload=
        '''Herunterladen=
        '''msgUpdateInstallierenAdmin=Du har hentet en opdatering men den er endnu ikke installeret.\n\n Start {0} som Admini [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Danish() As String
            Get
                Return ResourceManager.GetString("Danish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Nederlands
        '''msgUpdateBereitsVorhanden=Er is een update beschikbaar!\n\nStart {0} om het te installeren.
        '''msgUpdateLokaleInstallationNichtVollständig=
        '''Update={0} Update
        '''msgUpdateVorhanden=Update versie {0} is beschikbaar.\n\nWilt u het downloaden?
        '''ShowReleasenotes=
        '''WarningNetFrameworkTooOld=
        '''WarningNetFrameworkUnknown=
        '''NetFrameworkDownload=
        '''Herunterladen=
        '''msgUpdateInstallierenAdmin=U hebt een update gedownload maar nog niet geïnstalleerd.\n\n Start {0} als administrator om het te inst [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Dutch() As String
            Get
                Return ResourceManager.GetString("Dutch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=English
        '''msgUpdateBereitsVorhanden=You have already downloaded an update.\n\nRestart {0} to install it.
        '''msgUpdateLokaleInstallationNichtVollständig=The local installation is not complete.\n\nPlease download the program manually and reinstall it.
        '''Update={0} update
        '''msgUpdateVorhanden=Update to version {0} is available.\n\nDo you want to download it now?
        '''ShowReleasenotes=Show release notes
        '''WarningNetFrameworkTooOld=Warning: Install .Net Framework {0} (or an equivalent Mono version) before  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property English() As String
            Get
                Return ResourceManager.GetString("English", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Eesti
        '''msgUpdateBereitsVorhanden=
        '''msgUpdateLokaleInstallationNichtVollständig=
        '''Update=
        '''msgUpdateVorhanden=Saadaval on uuendus versioonile {0}.\n\nKas soovite selle alla laadida?
        '''ShowReleasenotes=
        '''WarningNetFrameworkTooOld=
        '''WarningNetFrameworkUnknown=
        '''NetFrameworkDownload=Laadi alla .Net Framework
        '''Herunterladen=
        '''msgUpdateInstallierenAdmin=
        '''msgKeinUpdate=Uuendusi ei ole saadaval
        '''msgFehlerUpdateSuchen=
        '''lblAktuelleDatei=
        '''UpdateFertigstellen=Lõpuleviimine...
        '''msgUpdateErfolgreich=
        '''N [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Estonian() As String
            Get
                Return ResourceManager.GetString("Estonian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Français
        '''msgUpdateBereitsVorhanden=Il y a déjà une mise à jour.\n\nRedémarrez {0} pour l’installer.
        '''msgUpdateLokaleInstallationNichtVollständig=
        '''Update=Mise à jour de {0}
        '''msgUpdateVorhanden=Une mise à jour à version {0} est disponible.\n\nVoulez vous la télécharger maintenant?
        '''ShowReleasenotes=
        '''WarningNetFrameworkTooOld=
        '''WarningNetFrameworkUnknown=
        '''NetFrameworkDownload=Télécharger .Net Framework
        '''Herunterladen=&amp;Télécharger
        '''msgUpdateInstallierenAdmin=Vous avez téléchargé une mise à j [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property French() As String
            Get
                Return ResourceManager.GetString("French", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Deutsch
        '''msgUpdateBereitsVorhanden=Es ist bereits ein Update vorhanden!\n\nStarten Sie {0} neu, um es zu installieren.
        '''msgUpdateLokaleInstallationNichtVollständig=Die lokale Installation ist nicht vollständig. Bitte laden Sie das Programm manuell herunter und installieren Sie es neu.
        '''Update={0} Update
        '''msgUpdateVorhanden=Ein Update auf Version {0} ist vorhanden.\n\nWollen Sie dieses jetzt herunterladen?
        '''ShowReleasenotes=Zeige Neuigkeiten
        '''WarningNetFrameworkTooOld=Warnung: Die Installatio [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property German() As String
            Get
                Return ResourceManager.GetString("German", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Ελληνικά
        '''msgUpdateBereitsVorhanden=Έχετε κατεβάσει μία αναβάθμιση.\n\nΕπανεκίνηση {0} για εγκατάσταση.
        '''msgUpdateLokaleInstallationNichtVollständig=
        '''Update={0} Αναβάθμιση
        '''msgUpdateVorhanden=Μία αναβάθμιση στην έκδοση {0} είναι διαθέσιμη.\n\nΘέλετε να την κατεβάσετε τώρα;
        '''ShowReleasenotes=
        '''WarningNetFrameworkTooOld=
        '''WarningNetFrameworkUnknown=
        '''NetFrameworkDownload=
        '''Herunterladen=
        '''msgUpdateInstallierenAdmin=Έχετε κατεβάσει μία αναβάθμιση αλλά δεν την έχετε εγκαταστήσει.\n\n Έναρξη {0} [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Greek() As String
            Get
                Return ResourceManager.GetString("Greek", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Polski
        '''msgUpdateBereitsVorhanden=Już pobrałeś aktualizacje!\n\nUruchom ponownie {0}, żeby się zainstalowała.
        '''msgUpdateLokaleInstallationNichtVollständig=
        '''Update={0} Aktualizacja
        '''msgUpdateVorhanden=Aktualizacja do wersji {0} istnieje.\n\nChcesz ją pobrać teraz?
        '''ShowReleasenotes=
        '''WarningNetFrameworkTooOld=
        '''WarningNetFrameworkUnknown=
        '''NetFrameworkDownload=
        '''Herunterladen=
        '''msgUpdateInstallierenAdmin=Pobrałeś aktualizacje, ale jej jeszcze nie wgrałeś.\n\nUruchom program {0} jako Administ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Polish() As String
            Get
                Return ResourceManager.GetString("Polish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Português
        '''msgUpdateBereitsVorhanden=Você já baixou uma atualização.\n\nReinicie {0} para instalá-la.
        '''msgUpdateLokaleInstallationNichtVollständig=A instalação local não está completa.\n\nPor favor, baixe o programa manualmente e reinstale-o
        '''Update={0} atualização
        '''msgUpdateVorhanden=Atualização para a versão {0} está disponível.\n\nVocê quer baixá-la agora?
        '''ShowReleasenotes=Exibir notas da versão
        '''WarningNetFrameworkTooOld=Atenção: Instale o .Net Framework {0} (ou uma versão Mono equivale [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Portuguese() As String
            Get
                Return ResourceManager.GetString("Portuguese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Srpski
        '''msgUpdateBereitsVorhanden=Jedan Update postoji.\n\nRestartujte{0}da bi ažurirali program
        '''msgUpdateLokaleInstallationNichtVollständig=
        '''Update={0} Ažuriranje
        '''msgUpdateVorhanden=Postoji jedan Update za verziju {0}.\n\nŽelite li skinuti Update?
        '''ShowReleasenotes=
        '''WarningNetFrameworkTooOld=
        '''WarningNetFrameworkUnknown=
        '''NetFrameworkDownload=
        '''Herunterladen=
        '''msgUpdateInstallierenAdmin=Upravo ste skinuliUpdate ali ga još niste izvršili.\n\nPokrenite {0}program kao Administrator da bi i [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Serbian() As String
            Get
                Return ResourceManager.GetString("Serbian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Español
        '''msgUpdateBereitsVorhanden=Ya existe una actualización!\n\nReiniciar {0} para instalar.
        '''msgUpdateLokaleInstallationNichtVollständig=
        '''Update={0} actualización
        '''msgUpdateVorhanden=Una actualización a la versión {0} existe.\n\nDesea bajarla?
        '''ShowReleasenotes=
        '''WarningNetFrameworkTooOld=
        '''WarningNetFrameworkUnknown=
        '''NetFrameworkDownload=
        '''Herunterladen=
        '''msgUpdateInstallierenAdmin=Ha bajado una actualización pero no esta instalada.\n\nInicie el programa de administrador para instalar [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Spanish() As String
            Get
                Return ResourceManager.GetString("Spanish", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
