'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FloseCode.UpdateLib.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Boarisch
        '''msgUpdateBereitsVorhanden=Es gibt scho a Update!{0}Zum Installiern, muasst as {1} Programm neistartn.
        '''Update=Neie Version vom {0} Programm
        '''msgUpdateVorhanden=Es gibt a Update auf Version {0}.{1}Mogst des jetz obalon?
        '''msgUpdateInstallierenAdmin=Sie hom grod a Update obaglon.\n\nStartens as {0} Programm ois Admin ums Update zum installiern.
        '''msgKeinUpdate=Koa neie Version do
        '''msgFehlerUpdateSuchen=Fella beim Updatesuacha: {0}
        '''lblAktuelleDatei=Datei: {0}
        '''UpdateFertigstellen=Ferti [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Bavarian() As String
            Get
                Return ResourceManager.GetString("Bavarian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Български
        '''msgUpdateBereitsVorhanden=Ъпдейтът вече е свален!{0}Рестартирайте {1}, за да го инсталирате.
        '''Update={0} ъпдейт
        '''msgUpdateVorhanden=Съществува ъпдейт на версия {0}.{1}Искате ли да го свалите сега?
        '''msgUpdateInstallierenAdmin=Вече сте свалили един ъпдейт, но не сте го инсталирали.\n\nСтартирайте програмата {0} като администратор, за да инсталирате ъпдейта.
        '''msgKeinUpdate=Не съществува ъпдейт
        '''msgFehlerUpdateSuchen=Грешка при търсенето на ъпдейт: {0}
        '''lblAktuelleDatei=Актуален файл: [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Bulgarian() As String
            Get
                Return ResourceManager.GetString("Bulgarian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=汉语
        '''msgUpdateBereitsVorhanden=你已下载了的更新。{0}重新启动{1}来安装它。
        '''Update={0}更新
        '''msgUpdateVorhanden=有一个更新版本{0}{1}你想现在就下载吗？
        '''msgUpdateInstallierenAdmin=您已下载了一个更新，但是你还没有安装了它。\n\n启动{0}以管理员身份来安装更新。
        '''msgKeinUpdate=现在没有更新
        '''msgFehlerUpdateSuchen=出错搜索更新的时候：{0}
        '''lblAktuelleDatei=当前文件：{0}
        '''UpdateFertigstellen=完成制订... ...
        '''msgUpdateErfolgreich=成功了下载更新！{0}若要安装此更新，您必须重新启动{1}{0}现在重新启动？
        '''msgFehlerUpdate=误差，更新的时候：{0}
        '''FehlerAusführen=尝试执行时发生错误&apos;{0}&apos;：\n\n{1}
        '''MonoUpdateHinweis=如果更新不启动，请运行以下命令：\n\n{0}
        '''UpdateHistory=更新的历 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Chinese() As String
            Get
                Return ResourceManager.GetString("Chinese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Dansk
        '''msgUpdateBereitsVorhanden=Du har allerede hentet en opdatering.{0}Genstart {1}for at installere.
        '''Update={0} opdater
        '''msgUpdateVorhanden=Opdatering til version {0}er nu tilgængelig.{1}Ønsker du at hente den nu?
        '''msgUpdateInstallierenAdmin=Du har hentet en opdatering men den er endnu ikke installeret.\n\n Start {0} som Administrator for at installere opdateringen.
        '''msgKeinUpdate=Ingen opdatering tilgængelig
        '''msgFehlerUpdateSuchen=Fejl under søgning efter opdatering: {0}
        '''lblAktuelleDat [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Danish() As String
            Get
                Return ResourceManager.GetString("Danish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Nederlands
        '''msgUpdateBereitsVorhanden=Er is een update beschikbaar!{0}Start {1} om het te installeren.
        '''Update={0} Update
        '''msgUpdateVorhanden=Update versie {0} is beschikbaar.{1}Wilt u het downloaden?
        '''msgUpdateInstallierenAdmin=U hebt een update gedownload maar nog niet geïnstalleerd.\n\n Start {0} als administrator om het te installeren.
        '''msgKeinUpdate=Geen updates beschikbaar
        '''msgFehlerUpdateSuchen=Fout bij het zoeken naar updates: {0}
        '''lblAktuelleDatei=Huidig bestand: {0}
        '''UpdateFertigst [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Dutch() As String
            Get
                Return ResourceManager.GetString("Dutch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=English
        '''msgUpdateBereitsVorhanden=You have already downloaded an update.{0} Restart {1} to install it.
        '''Update={0} update
        '''msgUpdateVorhanden=Update to version {0} is available.{1}Do you want to download it now?
        '''msgUpdateInstallierenAdmin=You have downloaded an update but have not installed it yet.\n\n Start {0} as administrator to install the update.
        '''msgKeinUpdate=No update available
        '''msgFehlerUpdateSuchen=Error while searching updates: {0}
        '''lblAktuelleDatei=Current file: {0}
        '''UpdateFert [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property English() As String
            Get
                Return ResourceManager.GetString("English", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Français
        '''msgUpdateBereitsVorhanden=Il y a déjà une mise à jour.{0} Redémarrez {1} pour l’installer.
        '''Update=Mise à jour de {0}
        '''msgUpdateVorhanden=Une mise à jour à version {0} est disponible.{1}Voulez vous la télécharger maintenant?
        '''msgUpdateInstallierenAdmin=Vous avez téléchargé une mise à jour.\n\nLance le logiciel {0} comme administrateur pour la installer.
        '''msgKeinUpdate=Il n’y a pas de mise à jour.
        '''msgFehlerUpdateSuchen=Erreur à chercher une mise à jour: {0}
        '''lblAktuelleDatei=Fichie [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property French() As String
            Get
                Return ResourceManager.GetString("French", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Deutsch
        '''msgUpdateBereitsVorhanden=Es ist bereits ein Update vorhanden!{0}Starten Sie {1} neu, um es zu installieren.
        '''Update={0} Update
        '''msgUpdateVorhanden=Ein Update auf Version {0} ist vorhanden.{1}Wollen Sie dieses jetzt herunterladen?
        '''msgUpdateInstallierenAdmin=Sie haben ein Update heruntergeladen aber noch nicht installiert.\n\nStarten Sie das {0} Programm als Administrator um das Update zu installieren.
        '''msgKeinUpdate=Kein Update vorhanden
        '''msgFehlerUpdateSuchen=Fehler beim Updatesuc [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property German() As String
            Get
                Return ResourceManager.GetString("German", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Ελληνικά
        '''msgUpdateBereitsVorhanden=Έχετε κατεβάσει μία αναβάθμιση.{0}Επανεκίνηση {1} για εγκατάσταση.
        '''Update={0} Αναβάθμιση
        '''msgUpdateVorhanden=Μία αναβάθμιση στην έκδοση {0} είναι διαθέσιμη.{1}Θέλετε να την κατεβάσετε τώρα;
        '''msgUpdateInstallierenAdmin=Έχετε κατεβάσει μία αναβάθμιση αλλά δεν την έχετε εγκαταστήσει.\n\n Έναρξη {0} ως διαχειριστής για εγκατάσταση.
        '''msgKeinUpdate=Καμμία διαθέσιμη αναβάθμιση
        '''msgFehlerUpdateSuchen=Σφάλμα κατά την αναζήτηση αναβαθμίσεων: {0}
        '''lblAktuelleDatei=Τ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Greek() As String
            Get
                Return ResourceManager.GetString("Greek", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Polski
        '''msgUpdateBereitsVorhanden=Już pobrałeś aktualizacje!{0}Uruchom ponownie {1}, żeby się zainstalowała.
        '''Update={0} Aktualizacja
        '''msgUpdateVorhanden=Aktualizacja do wersji {0} istnieje.{1}Chcesz ją pobrać teraz?
        '''msgUpdateInstallierenAdmin=Pobrałeś aktualizacje, ale jej jeszcze nie wgrałeś.\n\nUruchom program {0} jako Administrator żeby zainstalować aktualizacje.
        '''msgKeinUpdate=Brak Aktualizacji
        '''msgFehlerUpdateSuchen=Błąd wyszukiwania aktualizacji: {0}
        '''lblAktuelleDatei=Aktualny plik:  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Polish() As String
            Get
                Return ResourceManager.GetString("Polish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Português
        '''msgUpdateBereitsVorhanden=Você já baixou uma atualização.{0}Reinicie {1} para instalá-la.
        '''Update={0} atualização
        '''msgUpdateVorhanden=Atualização para a versão {0} está disponível.{1}Você quer baixá-la agora?
        '''msgUpdateInstallierenAdmin=Você baixou uma atualização mas ela ainda não foi instalada.\n\n Inicie {0} como administrador para instalar a atualização.
        '''msgKeinUpdate=Nenhuma atualização disponível.
        '''msgFehlerUpdateSuchen=Erro durante a procura por atualizações: {0}
        '''lblAktue [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Portuguese() As String
            Get
                Return ResourceManager.GetString("Portuguese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Srpski
        '''msgUpdateBereitsVorhanden=Jedan Update postoji.{0}Restartujte{1}da bi ažurirali program
        '''Update={0} Ažuriranje
        '''msgUpdateVorhanden=Postoji jedan Update za verziju {0}.\n\nŽelite li skinuti Update?
        '''msgUpdateInstallierenAdmin=Upravo ste skinuliUpdate ali ga još niste izvršili.\n\nPokrenite {0}program kao Administrator da bi izvršili Update
        '''msgKeinUpdate=Nema novih Update-a
        '''msgFehlerUpdateSuchen=Greška kod traženja Update-a: {0}
        '''lblAktuelleDatei=Aktuelni fajl: {0}
        '''UpdateFertigstell [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Serbian() As String
            Get
                Return ResourceManager.GetString("Serbian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''SprachenName=Español
        '''msgUpdateBereitsVorhanden=Ya existe una actualización!{0}Reiniciar {1} para instalar.
        '''Update={0} actualización
        '''msgUpdateVorhanden=Una actualización a la versión {0} existe.{1}Desea bajarla?
        '''msgUpdateInstallierenAdmin=Ha bajado una actualización pero no esta instalada.\n\nInicie el programa de administrador para instalar la actualización.
        '''msgKeinUpdate=No hay actualización
        '''msgFehlerUpdateSuchen=Fallo en la búsqueda de actualización: {0}
        '''lblAktuelleDatei=Archivo actual: {0}
        '''Upd [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Spanish() As String
            Get
                Return ResourceManager.GetString("Spanish", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
